const express=require('express'),db=require('../db');
const {authenticate,roles,schoolBoundary}=require('../middleware/auth');
const router=express.Router();
router.use(authenticate);

const cycleDays={MONTHLY:30,TERMLY:120,QUARTERLY:90,HALF_YEARLY:182,ANNUAL:365};
function addCycle(d,cycle){const x=new Date(`${d}T00:00:00Z`);if(cycle==='MONTHLY')x.setUTCMonth(x.getUTCMonth()+1);else if(cycle==='TERMLY')x.setUTCMonth(x.getUTCMonth()+4);else if(cycle==='QUARTERLY')x.setUTCMonth(x.getUTCMonth()+3);else if(cycle==='HALF_YEARLY')x.setUTCMonth(x.getUTCMonth()+6);else if(cycle==='ANNUAL')x.setUTCFullYear(x.getUTCFullYear()+1);else x.setUTCDate(x.getUTCDate()+30);return x.toISOString().slice(0,10)}
function invoiceStatus(row){if(row.status==='PAID'||row.status==='WAIVED'||row.status==='CANCELLED'||row.status==='FAILED')return row.status;const due=new Date(`${row.due_on}T23:59:59Z`),today=new Date();if(Number(row.amount_paid||0)>=Number(row.amount||0))return 'PAID';if(Number(row.amount_paid||0)>0&&due<today)return 'PARTIALLY_PAID';if(due<today)return 'OVERDUE';const ms=due-today;if(ms<=7*86400000)return 'DUE_SOON';if(row.status==='PENDING_VERIFICATION')return 'PENDING_VERIFICATION';return Number(row.amount_paid||0)>0?'PARTIALLY_PAID':'DUE'}

// Platform Owner: billing catalogue and school billing control.
router.get('/owner/overview',roles('PLATFORM_OWNER'),async(req,res)=>{try{
 const [schools,plans,methods,inv]=await Promise.all([
  db.query(`SELECT s.id,s.code,s.name,s.status,ss.id subscription_id,ss.plan_name_snapshot,ss.amount,ss.currency,ss.billing_cycle,ss.starts_on,ss.next_due_on,ss.grace_days,ss.status subscription_status,
    (SELECT count(*) FROM billing_invoices bi WHERE bi.school_id=s.id AND bi.status NOT IN ('PAID','WAIVED','CANCELLED'))::int open_invoices,
    (SELECT COALESCE(sum(bi.amount-bi.amount_paid),0) FROM billing_invoices bi WHERE bi.school_id=s.id AND bi.status IN ('DUE','DUE_SOON','OVERDUE','PARTIALLY_PAID')) outstanding
    FROM schools s LEFT JOIN LATERAL (SELECT * FROM school_subscriptions x WHERE x.school_id=s.id ORDER BY CASE WHEN x.status IN ('ACTIVE','TRIAL','PAUSED') THEN 0 ELSE 1 END,x.created_at DESC LIMIT 1) ss ON true ORDER BY s.created_at DESC`),
  db.query(`SELECT * FROM billing_plans WHERE is_active ORDER BY name`),
  db.query(`SELECT * FROM platform_payment_methods WHERE is_active ORDER BY sort_order,name`),
  db.query(`SELECT bi.*,s.name school_name FROM billing_invoices bi JOIN schools s ON s.id=bi.school_id ORDER BY bi.due_on DESC,bi.created_at DESC LIMIT 200`)
 ]);
 inv.rows.forEach(x=>x.computed_status=invoiceStatus(x));
 const summary={schools:schools.rowCount,active:schools.rows.filter(x=>x.status==='ACTIVE').length,overdue:inv.rows.filter(x=>x.computed_status==='OVERDUE').length,due_soon:inv.rows.filter(x=>x.computed_status==='DUE_SOON').length,pending:inv.rows.filter(x=>x.computed_status==='PENDING_VERIFICATION').length,outstanding:inv.rows.filter(x=>['DUE','DUE_SOON','OVERDUE','PARTIALLY_PAID'].includes(x.computed_status)).reduce((a,x)=>a+Number(x.amount||0)-Number(x.amount_paid||0),0)};
 res.json({summary,schools:schools.rows,plans:plans.rows,methods:methods.rows,invoices:inv.rows});
}catch(e){console.error(e);res.status(500).json({error:'Unable to load billing centre'})}});

router.post('/owner/plans',roles('PLATFORM_OWNER'),async(req,res)=>{try{const b=req.body;if(!b.code||!b.name)return res.status(400).json({error:'Plan code and name are required'});const q=await db.query(`INSERT INTO billing_plans(code,name,description,amount,currency,billing_cycle,grace_days) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[String(b.code).trim().toUpperCase(),b.name,b.description||'',Number(b.amount||0),b.currency||'KES',b.billing_cycle||'ANNUAL',Number(b.grace_days??7)]);res.status(201).json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});
router.patch('/owner/plans/:id',roles('PLATFORM_OWNER'),async(req,res)=>{try{const b=req.body,q=await db.query(`UPDATE billing_plans SET name=COALESCE($2,name),description=COALESCE($3,description),amount=COALESCE($4,amount),currency=COALESCE($5,currency),billing_cycle=COALESCE($6,billing_cycle),grace_days=COALESCE($7,grace_days),is_active=COALESCE($8,is_active),updated_at=now() WHERE id=$1 RETURNING *`,[req.params.id,b.name,b.description,b.amount,b.currency,b.billing_cycle,b.grace_days,b.is_active]);if(!q.rows[0])return res.status(404).json({error:'Plan not found'});res.json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});
router.patch('/owner/payment-methods/:id',roles('PLATFORM_OWNER'),async(req,res)=>{try{const b=req.body,q=await db.query(`UPDATE platform_payment_methods SET name=COALESCE($2,name),instructions=COALESCE($3,instructions),is_active=COALESCE($4,is_active),sort_order=COALESCE($5,sort_order),updated_at=now() WHERE id=$1 RETURNING *`,[req.params.id,b.name,b.instructions,b.is_active,b.sort_order]);if(!q.rows[0])return res.status(404).json({error:'Payment method not found'});res.json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});

router.post('/owner/schools/:schoolId/subscription',roles('PLATFORM_OWNER'),async(req,res)=>{const c=await db.pool.connect();try{const b=req.body,plan=(await c.query('SELECT * FROM billing_plans WHERE id=$1 AND is_active',[b.plan_id])).rows[0];if(!plan)throw Error('Active billing plan not found');const school=(await c.query('SELECT id FROM schools WHERE id=$1',[req.params.schoolId])).rows[0];if(!school)throw Error('School not found');await c.query('BEGIN');await c.query(`UPDATE school_subscriptions SET status='EXPIRED',updated_at=now() WHERE school_id=$1 AND status IN ('ACTIVE','TRIAL','PAUSED')`,[req.params.schoolId]);const start=b.starts_on||new Date().toISOString().slice(0,10),due=b.next_due_on||addCycle(start,plan.billing_cycle);const sub=(await c.query(`INSERT INTO school_subscriptions(school_id,plan_id,plan_name_snapshot,amount,currency,billing_cycle,starts_on,next_due_on,grace_days,status,notes) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,'ACTIVE',$10) RETURNING *`,[req.params.schoolId,plan.id,plan.name,plan.amount,plan.currency,plan.billing_cycle,start,due,plan.grace_days,b.notes||''])).rows[0];if(b.create_invoice!==false){const count=(await c.query('SELECT count(*)::int n FROM billing_invoices')).rows[0].n+1;const invNo=`INV-${new Date().getUTCFullYear()}-${String(count).padStart(4,'0')}`;await c.query(`INSERT INTO billing_invoices(school_id,subscription_id,invoice_no,description,amount,currency,issued_on,due_on,status) VALUES($1,$2,$3,$4,$5,$6,CURRENT_DATE,$7,'DUE')`,[req.params.schoolId,sub.id,invNo,`${plan.name} subscription`,plan.amount,plan.currency,due])}await c.query('COMMIT');res.status(201).json(sub)}catch(e){await c.query('ROLLBACK').catch(()=>{});res.status(400).json({error:e.message})}finally{c.release()}});

router.post('/owner/invoices',roles('PLATFORM_OWNER'),async(req,res)=>{try{const b=req.body;if(!b.school_id||!b.amount||!b.due_on)return res.status(400).json({error:'School, amount and due date are required'});const count=(await db.query('SELECT count(*)::int n FROM billing_invoices')).rows[0].n+1;const invNo=b.invoice_no||`INV-${new Date().getUTCFullYear()}-${String(count).padStart(4,'0')}`;const q=await db.query(`INSERT INTO billing_invoices(school_id,subscription_id,invoice_no,description,amount,currency,issued_on,due_on,status,notes) VALUES($1,$2,$3,$4,$5,$6,COALESCE($7::date,CURRENT_DATE),$8,'DUE',$9) RETURNING *`,[b.school_id,b.subscription_id||null,invNo,b.description||'PRO-MARK subscription',Number(b.amount),b.currency||'KES',b.issued_on||null,b.due_on,b.notes||'']);res.status(201).json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});

router.post('/owner/invoices/:invoiceId/payment',roles('PLATFORM_OWNER'),async(req,res)=>{const c=await db.pool.connect();try{const b=req.body;const inv=(await c.query('SELECT * FROM billing_invoices WHERE id=$1',[req.params.invoiceId])).rows[0];if(!inv)throw Error('Invoice not found');const pm=b.payment_method_id?(await c.query('SELECT * FROM platform_payment_methods WHERE id=$1',[b.payment_method_id])).rows[0]:null;await c.query('BEGIN');const pay=(await c.query(`INSERT INTO billing_payments(school_id,invoice_id,payment_method_id,payment_method_name_snapshot,amount,currency,reference,payment_date,status,recorded_by,verified_by,verified_at,notes) VALUES($1,$2,$3,$4,$5,$6,$7,COALESCE($8::date,CURRENT_DATE),'CONFIRMED',$9,$9,now(),$10) RETURNING *`,[inv.school_id,inv.id,b.payment_method_id||null,pm?.name||b.payment_method||'Manual',Number(b.amount),inv.currency,b.reference||'',b.payment_date||null,req.user.user_id,b.notes||''])).rows[0];const paid=(await c.query(`SELECT COALESCE(sum(amount),0) total FROM billing_payments WHERE invoice_id=$1 AND status='CONFIRMED'`,[inv.id])).rows[0].total;const status=Number(paid)>=Number(inv.amount)?'PAID':'PARTIALLY_PAID';const updated=(await c.query(`UPDATE billing_invoices SET amount_paid=$2,status=$3,updated_at=now() WHERE id=$1 RETURNING *`,[inv.id,paid,status])).rows[0];await c.query(`UPDATE school_subscriptions SET next_due_on=CASE WHEN $2='PAID' THEN CASE billing_cycle WHEN 'MONTHLY' THEN next_due_on+INTERVAL '1 month' WHEN 'TERMLY' THEN next_due_on+INTERVAL '4 months' WHEN 'QUARTERLY' THEN next_due_on+INTERVAL '3 months' WHEN 'HALF_YEARLY' THEN next_due_on+INTERVAL '6 months' WHEN 'ANNUAL' THEN next_due_on+INTERVAL '1 year' ELSE next_due_on+INTERVAL '30 days' END ELSE next_due_on END,updated_at=now() WHERE id=$3`,[inv.school_id,status,inv.subscription_id]);await c.query('COMMIT');res.status(201).json({payment:pay,invoice:updated})}catch(e){await c.query('ROLLBACK').catch(()=>{});res.status(400).json({error:e.message})}finally{c.release()}});

router.post('/owner/invoices/:invoiceId/alert',roles('PLATFORM_OWNER'),async(req,res)=>{try{const inv=(await db.query('SELECT * FROM billing_invoices WHERE id=$1',[req.params.invoiceId])).rows[0];if(!inv)return res.status(404).json({error:'Invoice not found'});const b=req.body;const q=await db.query(`INSERT INTO billing_notifications(school_id,invoice_id,title,message,severity,sent_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[inv.school_id,inv.id,b.title||'PRO-MARK subscription payment reminder',b.message||`Your PRO-MARK invoice ${inv.invoice_no} of ${inv.currency} ${Number(inv.amount).toFixed(2)} is due on ${inv.due_on}. Please arrange payment.`,b.severity||'WARNING',req.user.user_id]);res.status(201).json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});

// School portal: billing summary, invoices, payment instructions and notification acknowledgement.
router.get('/:schoolId/summary',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN','HEADTEACHER'),async(req,res)=>{try{const [sub,inv,methods,notes]=await Promise.all([
 db.query(`SELECT ss.*,bp.description plan_description FROM school_subscriptions ss LEFT JOIN billing_plans bp ON bp.id=ss.plan_id WHERE ss.school_id=$1 AND ss.status IN ('ACTIVE','TRIAL','PAUSED') ORDER BY ss.created_at DESC LIMIT 1`,[req.params.schoolId]),
 db.query(`SELECT * FROM billing_invoices WHERE school_id=$1 ORDER BY due_on DESC,created_at DESC LIMIT 50`,[req.params.schoolId]),
 db.query(`SELECT * FROM platform_payment_methods WHERE is_active ORDER BY sort_order,name`),
 db.query(`SELECT * FROM billing_notifications WHERE school_id=$1 AND status='UNREAD' ORDER BY sent_at DESC LIMIT 20`,[req.params.schoolId])
]);inv.rows.forEach(x=>x.computed_status=invoiceStatus(x));res.json({subscription:sub.rows[0]||null,invoices:inv.rows,methods:methods.rows,notifications:notes.rows});}catch(e){res.status(500).json({error:'Unable to load billing information'})}});
router.post('/:schoolId/invoices/:invoiceId/payment-request',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN'),async(req,res)=>{try{const inv=(await db.query('SELECT * FROM billing_invoices WHERE id=$1 AND school_id=$2',[req.params.invoiceId,req.params.schoolId])).rows[0];if(!inv)return res.status(404).json({error:'Invoice not found'});const b=req.body;if(!b.amount||Number(b.amount)<=0)return res.status(400).json({error:'Payment amount is required'});const pm=b.payment_method_id?(await db.query('SELECT * FROM platform_payment_methods WHERE id=$1',[b.payment_method_id])).rows[0]:null;const q=await db.query(`INSERT INTO billing_payments(school_id,invoice_id,payment_method_id,payment_method_name_snapshot,amount,currency,reference,payment_date,status,recorded_by,notes) VALUES($1,$2,$3,$4,$5,$6,$7,COALESCE($8::date,CURRENT_DATE),'PENDING_VERIFICATION',$9,$10) RETURNING *`,[req.params.schoolId,inv.id,b.payment_method_id||null,pm?.name||b.payment_method||'Manual',Number(b.amount),inv.currency,b.reference||'',b.payment_date||null,req.user.user_id,b.notes||'']);await db.query(`UPDATE billing_invoices SET status='PENDING_VERIFICATION',updated_at=now() WHERE id=$1 AND status<>'PAID'`,[inv.id]);res.status(201).json(q.rows[0])}catch(e){res.status(400).json({error:e.message})}});
router.patch('/:schoolId/notifications/:id/read',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN','HEADTEACHER'),async(req,res)=>{const q=await db.query(`UPDATE billing_notifications SET status='READ',read_at=now() WHERE id=$1 AND school_id=$2 RETURNING *`,[req.params.id,req.params.schoolId]);if(!q.rows[0])return res.status(404).json({error:'Notification not found'});res.json(q.rows[0])});

module.exports=router;
