const express=require('express'),db=require('../db'),fs=require('fs'),path=require('path'),multer=require('multer');
const {authenticate,roles,schoolBoundary}=require('../middleware/auth');
const router=express.Router();router.use(authenticate);
const root=path.join(__dirname,'..','..','uploads','resources');
const storage=multer.memoryStorage();
const allowedMimes=new Set(['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-excel','application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation','text/plain']);
const upload=multer({storage,limits:{fileSize:20*1024*1024},fileFilter:(req,file,cb)=>{const ext=/\.[a-z0-9]+$/i.test(file.originalname)?file.originalname.match(/\.[a-z0-9]+$/i)[0].toLowerCase():'';const ok=allowedMimes.has(file.mimetype)||['.pdf','.doc','.docx','.xls','.xlsx','.ppt','.pptx','.txt'].includes(ext);cb(ok?null:new Error('Supported resources: PDF, Word, Excel, PowerPoint or text files.'),ok);}});
function safeName(name){return String(name||'resource').replace(/[^a-z0-9._-]/gi,'_')}
function mimeFor(name,mime){if(mime&&mime!=='application/octet-stream')return mime;const ext=String(name||'').toLowerCase().match(/\.[a-z0-9]+$/)?.[0];return ({'.pdf':'application/pdf','.doc':'application/msword','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document','.xls':'application/vnd.ms-excel','.xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','.ppt':'application/vnd.ms-powerpoint','.pptx':'application/vnd.openxmlformats-officedocument.presentationml.presentation','.txt':'text/plain'})[ext]||'application/octet-stream';}
router.get('/:schoolId',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN','HEADTEACHER','DEPUTY_HEADTEACHER','SENIOR_TEACHER','CLASS_TEACHER','TEACHER'),async(req,res)=>{try{res.json((await db.query(`SELECT r.*,s.code AS subject_code,s.name AS subject_name,c.name AS class_name,c.stream,ay.year_label FROM school_resource_documents r LEFT JOIN subjects s ON s.id=r.subject_id LEFT JOIN classes c ON c.id=r.class_id LEFT JOIN academic_years ay ON ay.id=r.academic_year_id WHERE r.school_id=$1 AND r.is_active=true ORDER BY CASE r.resource_type WHEN 'SCHEME_OF_WORK' THEN 1 WHEN 'NOTES' THEN 2 WHEN 'REVISION_PAPER' THEN 3 WHEN 'TEACHER_GUIDE' THEN 4 ELSE 5 END,COALESCE(s.name,''),COALESCE(c.name,''),r.title`,[req.params.schoolId])).rows)}catch(e){res.status(400).json({error:e.message})}});
router.post('/:schoolId',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN','PLATFORM_OWNER'),upload.single('file'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'Select a resource file.'});const type=String(req.body.resource_type||'PDF').toUpperCase();const allowed=['PDF','SCHEME_OF_WORK','NOTES','REVISION_PAPER','TEACHER_GUIDE','OTHER'];if(!allowed.includes(type))return res.status(400).json({error:'Invalid resource type.'});const subjectId=String(req.body.subject_id||'').trim()||null;const classId=String(req.body.class_id||'').trim()||null;const academicYearId=String(req.body.academic_year_id||'').trim()||null;const url=`/api/resources/${req.params.schoolId}/${encodeURIComponent(req.file.originalname)}`;
const mime=mimeFor(req.file.originalname,req.file.mimetype);if(subjectId){const ok=await db.query('SELECT 1 FROM subjects WHERE id=$1 AND school_id=$2',[subjectId,req.params.schoolId]);if(!ok.rows[0])return res.status(400).json({error:'Selected subject does not belong to this school.'});}if(classId){const ok=await db.query('SELECT 1 FROM classes WHERE id=$1 AND school_id=$2',[classId,req.params.schoolId]);if(!ok.rows[0])return res.status(400).json({error:'Selected class does not belong to this school.'});}if(academicYearId){const ok=await db.query('SELECT 1 FROM academic_years WHERE id=$1 AND school_id=$2',[academicYearId,req.params.schoolId]);if(!ok.rows[0])return res.status(400).json({error:'Selected academic year does not belong to this school.'});}const q=await db.query(`INSERT INTO school_resource_documents(school_id,title,resource_type,file_url,original_name,description,file_data,mime_type,subject_id,class_id,academic_year_id,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id,school_id,title,resource_type,file_url,original_name,description,mime_type,subject_id,class_id,academic_year_id,uploaded_by,created_at`,[req.params.schoolId,String(req.body.title||req.file.originalname).trim(),type,url,req.file.originalname,String(req.body.description||''),req.file.buffer,mime,subjectId,classId,academicYearId,req.user.user_id]);res.status(201).json(q.rows[0]);}catch(e){res.status(400).json({error:e.message})}});
router.get('/:schoolId/:id/file',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN','HEADTEACHER','DEPUTY_HEADTEACHER','SENIOR_TEACHER','CLASS_TEACHER','TEACHER','PLATFORM_OWNER'),async(req,res)=>{try{const q=await db.query(`SELECT original_name,mime_type,file_data FROM school_resource_documents WHERE id=$1 AND school_id=$2 AND is_active=true`,[req.params.id,req.params.schoolId]);if(!q.rows[0]||!q.rows[0].file_data)return res.status(404).json({error:'Resource file not found.'});res.setHeader('Content-Type',q.rows[0].mime_type||'application/pdf');const name=safeName(q.rows[0].original_name||'resource'); const mime=mimeFor(name,q.rows[0].mime_type); res.setHeader('Content-Type',mime); res.setHeader('Content-Disposition',`${mime==='application/pdf'?'inline':'attachment'}; filename="${name}"`); res.setHeader('Cache-Control','private, max-age=300'); res.end(q.rows[0].file_data);}catch(e){res.status(400).json({error:e.message})}});
router.delete('/:schoolId/:id',schoolBoundary,roles('SCHOOL_ADMIN','ADMIN','PLATFORM_OWNER'),async(req,res)=>{try{const q=await db.query(`UPDATE school_resource_documents SET is_active=false WHERE id=$1 AND school_id=$2 RETURNING id`,[req.params.id,req.params.schoolId]);if(!q.rows[0])return res.status(404).json({error:'Resource not found'});res.json({ok:true})}catch(e){res.status(400).json({error:e.message})}});
module.exports=router;
