const express=require("express"),db=require("../db"),fs=require("fs"),path=require("path"),multer=require("multer");
const {authenticate,roles,schoolBoundary}=require("../middleware/auth");
const router=express.Router();router.use(authenticate);
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:2*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpe?g|webp)$/.test(file.mimetype))});
const {dataUrl}=require("../services/assets");
router.get("/:schoolId/identity",schoolBoundary,async(req,res)=>{const q=await db.query(`SELECT s.name,s.code,t.code template_code,si.* FROM schools s JOIN school_templates t ON t.id=s.template_id JOIN school_identity si ON si.school_id=s.id WHERE s.id=$1`,[req.params.schoolId]);res.json(q.rows[0]||{});});
router.put("/:schoolId/identity",schoolBoundary,roles("SCHOOL_ADMIN","ADMIN"),async(req,res)=>{const b=req.body||{},name=String(b.school_name||"").trim();if(!name)return res.status(400).json({error:"School name is required."});const c=await db.pool.connect();try{await c.query("BEGIN");await c.query(`UPDATE schools SET name=$2,updated_at=now() WHERE id=$1`,[req.params.schoolId,name]);const q=await c.query(`UPDATE school_identity SET motto=COALESCE($2,motto),primary_color=COALESCE(NULLIF($3,''),primary_color),secondary_color=COALESCE(NULLIF($4,''),secondary_color),address=COALESCE($5,address),contact_phone=COALESCE($6,contact_phone),contact_email=COALESCE($7,contact_email),updated_at=now() WHERE school_id=$1 RETURNING *`,[req.params.schoolId,b.motto,b.primary_color,b.secondary_color,b.address,b.contact_phone,b.contact_email]);await c.query("COMMIT");res.json({...q.rows[0],school_name:name});}catch(e){await c.query("ROLLBACK");res.status(e.status||400).json({error:e.message});}finally{c.release();}});
router.post("/:schoolId/logo",schoolBoundary,roles("SCHOOL_ADMIN","ADMIN"),upload.single("logo"),async(req,res)=>{if(!req.file)return res.status(400).json({error:"Upload a PNG, JPG or WEBP logo up to 2MB"});const url=dataUrl(req.file.buffer,req.file.mimetype);const q=await db.query(`UPDATE school_identity SET logo_url=$2,updated_at=now() WHERE school_id=$1 RETURNING logo_url`,[req.params.schoolId,url]);res.json({logo_url:q.rows[0]?.logo_url,storage:"database"});});
module.exports=router;
