const fs=require('fs'),path=require('path'),child=require('child_process');
const root=path.join(__dirname,'..');
const required=['backend/server.js','backend/routes/auth.js','backend/routes/platform.js','backend/routes/school.js','backend/routes/settings.js','backend/routes/people.js','backend/routes/assessments.js','backend/routes/grading.js','backend/routes/merit.js','backend/routes/reports.js','backend/services/report-engine.js','backend/services/report-pdf.js','database/schema.sql','database/001_hardening.sql','public/index.html','public/login.html','public/owner.html','public/dashboard.html'];
for(const f of required)if(!fs.existsSync(path.join(root,f)))throw Error('Missing '+f);
const jsFiles=[];function walk(d){for(const n of fs.readdirSync(d)){const p=path.join(d,n),st=fs.statSync(p);if(st.isDirectory()&&!['node_modules','.git'].includes(n))walk(p);else if(/\.js$/.test(n))jsFiles.push(p);}}walk(root);for(const f of jsFiles){const r=child.spawnSync(process.execPath,['--check',f],{encoding:'utf8'});if(r.status)throw Error(`Syntax error in ${path.relative(root,f)}\n${r.stderr}`);}
const dash=fs.readFileSync(path.join(root,'public/dashboard.html'),'utf8');if(!dash.includes('Create year + Term 1–3'))throw Error('Academic year control missing');if(!dash.includes('id="teacherMarking"')||!dash.includes('id="markYear"')||!dash.includes('id="markTerm"')||!dash.includes('id="markAssessment"')||!dash.includes('id="markClass"')||!dash.includes('id="markSubject"'))throw Error('Teacher mark-entry controls missing');if(!dash.includes('id="userControl"')||!dash.includes('id="markControl"')||!dash.includes('id="assign"')||!dash.includes('id="classLists"'))throw Error('Administrator navigation controls missing');if(!dash.includes('peopleOpenAssignments')||!dash.includes('peopleOpenClassLists'))throw Error('People quick navigation controls missing.');
if(/section id="workflow" class="[^"]*nav-managed-section/.test(dash))throw Error('The #workflow shortcuts panel is a nav-managed-section again, which means it is permanently hidden (nothing ever calls showSection("workflow")).');
const merit=fs.readFileSync(path.join(root,'backend/routes/merit.js'),'utf8');
if(merit.includes('Intentional cover page'))throw Error('Merit PDF has reintroduced the near-empty cover page.');
const engine=fs.readFileSync(path.join(root,'backend/services/report-engine.js'),'utf8');if(!engine.includes('function autoSubjectComment'))throw Error('Report comment engine missing');console.log(`PRO-MARK smoke check passed: ${jsFiles.length} JavaScript files checked.`);
